/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Calendar Booking API
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  Booking,
  CreateBookingRequest,
  CreateEventTypeRequest,
  ErrorResponse,
  EventType,
  Slot,
  SlotsListParams,
  UpdateEventTypeRequest
} from '../model';





/**
 * List all upcoming bookings sorted by startTime ascending
 */
export type adminBookingsListResponse200 = {
  data: Booking[]
  status: 200
}

export type adminBookingsListResponseSuccess = (adminBookingsListResponse200) & {
  headers: Headers;
};
;

export type adminBookingsListResponse = (adminBookingsListResponseSuccess)

export const getAdminBookingsListUrl = () => {




  return `/api/admin/bookings`
}

export const adminBookingsList = async ( options?: RequestInit): Promise<adminBookingsListResponse> => {

  const res = await fetch(getAdminBookingsListUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminBookingsListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as adminBookingsListResponse
}





export const getAdminBookingsListQueryKey = () => {
    return [
    `/api/admin/bookings`
    ] as const;
    }


export const getAdminBookingsListQueryOptions = <TData = Awaited<ReturnType<typeof adminBookingsList>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof adminBookingsList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminBookingsListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminBookingsList>>> = ({ signal }) => adminBookingsList({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof adminBookingsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminBookingsListQueryResult = NonNullable<Awaited<ReturnType<typeof adminBookingsList>>>
export type AdminBookingsListQueryError = unknown



export function createAdminBookingsList<TData = Awaited<ReturnType<typeof adminBookingsList>>, TError = unknown>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof adminBookingsList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getAdminBookingsListQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}






/**
 * Create a booking. Returns 409 if slot is already taken, 404 if eventType not found.
 */
export type bookingsCreateResponse201 = {
  data: Booking
  status: 201
}

export type bookingsCreateResponse400 = {
  data: ErrorResponse
  status: 400
}

export type bookingsCreateResponse404 = {
  data: ErrorResponse
  status: 404
}

export type bookingsCreateResponse409 = {
  data: ErrorResponse
  status: 409
}

export type bookingsCreateResponseSuccess = (bookingsCreateResponse201) & {
  headers: Headers;
};
export type bookingsCreateResponseError = (bookingsCreateResponse400 | bookingsCreateResponse404 | bookingsCreateResponse409) & {
  headers: Headers;
};

export type bookingsCreateResponse = (bookingsCreateResponseSuccess | bookingsCreateResponseError)

export const getBookingsCreateUrl = () => {




  return `/api/bookings`
}

export const bookingsCreate = async (createBookingRequest: CreateBookingRequest, options?: RequestInit): Promise<bookingsCreateResponse> => {

  const res = await fetch(getBookingsCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createBookingRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: bookingsCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as bookingsCreateResponse
}




export const getBookingsCreateMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof bookingsCreate>>, TError,{data: CreateBookingRequest}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof bookingsCreate>>, TError,{data: CreateBookingRequest}, TContext> => {

const mutationKey = ['bookingsCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bookingsCreate>>, {data: CreateBookingRequest}> = (props) => {
          const {data} = props ?? {};

          return  bookingsCreate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BookingsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof bookingsCreate>>>
    export type BookingsCreateMutationBody = CreateBookingRequest
    export type BookingsCreateMutationError = ErrorResponse

    export const createBookingsCreate = <TError = ErrorResponse,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof bookingsCreate>>, TError,{data: CreateBookingRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof bookingsCreate>>,
        TError,
        {data: CreateBookingRequest},
        TContext
      > => {
      return createMutation(() => ({ ...getBookingsCreateMutationOptions(options?.()) }), queryClient);
    }
    /**
 * Get booking details by ID
 */
export type byIdGetResponse200 = {
  data: Booking
  status: 200
}

export type byIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type byIdGetResponseSuccess = (byIdGetResponse200) & {
  headers: Headers;
};
export type byIdGetResponseError = (byIdGetResponse404) & {
  headers: Headers;
};

export type byIdGetResponse = (byIdGetResponseSuccess | byIdGetResponseError)

export const getByIdGetUrl = (id: string,) => {




  return `/api/bookings/${id}`
}

export const byIdGet = async (id: string, options?: RequestInit): Promise<byIdGetResponse> => {

  const res = await fetch(getByIdGetUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: byIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as byIdGetResponse
}





export const getByIdGetQueryKey = (id: string,) => {
    return [
    `/api/bookings/${id}`
    ] as const;
    }


export const getByIdGetQueryOptions = <TData = Awaited<ReturnType<typeof byIdGet>>, TError = ErrorResponse>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof byIdGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getByIdGetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof byIdGet>>> = ({ signal }) => byIdGet(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof byIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ByIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof byIdGet>>>
export type ByIdGetQueryError = ErrorResponse



export function createByIdGet<TData = Awaited<ReturnType<typeof byIdGet>>, TError = ErrorResponse>(
 id: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof byIdGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getByIdGetQueryOptions(id(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}






/**
 * Cancel (delete) a booking by ID. Physically removes the record.
 */
export type byIdCancelResponse204 = {
  data: void
  status: 204
}

export type byIdCancelResponse404 = {
  data: ErrorResponse
  status: 404
}

export type byIdCancelResponseSuccess = (byIdCancelResponse204) & {
  headers: Headers;
};
export type byIdCancelResponseError = (byIdCancelResponse404) & {
  headers: Headers;
};

export type byIdCancelResponse = (byIdCancelResponseSuccess | byIdCancelResponseError)

export const getByIdCancelUrl = (id: string,) => {




  return `/api/bookings/${id}`
}

export const byIdCancel = async (id: string, options?: RequestInit): Promise<byIdCancelResponse> => {

  const res = await fetch(getByIdCancelUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: byIdCancelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as byIdCancelResponse
}




export const getByIdCancelMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof byIdCancel>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof byIdCancel>>, TError,{id: string}, TContext> => {

const mutationKey = ['byIdCancel'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof byIdCancel>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  byIdCancel(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ByIdCancelMutationResult = NonNullable<Awaited<ReturnType<typeof byIdCancel>>>

    export type ByIdCancelMutationError = ErrorResponse

    export const createByIdCancel = <TError = ErrorResponse,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof byIdCancel>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof byIdCancel>>,
        TError,
        {id: string},
        TContext
      > => {
      return createMutation(() => ({ ...getByIdCancelMutationOptions(options?.()) }), queryClient);
    }
    /**
 * List all event types
 */
export type eventTypesListResponse200 = {
  data: EventType[]
  status: 200
}

export type eventTypesListResponseSuccess = (eventTypesListResponse200) & {
  headers: Headers;
};
;

export type eventTypesListResponse = (eventTypesListResponseSuccess)

export const getEventTypesListUrl = () => {




  return `/api/event-types`
}

export const eventTypesList = async ( options?: RequestInit): Promise<eventTypesListResponse> => {

  const res = await fetch(getEventTypesListUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: eventTypesListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as eventTypesListResponse
}





export const getEventTypesListQueryKey = () => {
    return [
    `/api/event-types`
    ] as const;
    }


export const getEventTypesListQueryOptions = <TData = Awaited<ReturnType<typeof eventTypesList>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof eventTypesList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventTypesListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventTypesList>>> = ({ signal }) => eventTypesList({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof eventTypesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventTypesListQueryResult = NonNullable<Awaited<ReturnType<typeof eventTypesList>>>
export type EventTypesListQueryError = unknown



export function createEventTypesList<TData = Awaited<ReturnType<typeof eventTypesList>>, TError = unknown>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof eventTypesList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getEventTypesListQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}






/**
 * Create a new event type
 */
export type eventTypesCreateResponse201 = {
  data: EventType
  status: 201
}

export type eventTypesCreateResponse400 = {
  data: ErrorResponse
  status: 400
}

export type eventTypesCreateResponseSuccess = (eventTypesCreateResponse201) & {
  headers: Headers;
};
export type eventTypesCreateResponseError = (eventTypesCreateResponse400) & {
  headers: Headers;
};

export type eventTypesCreateResponse = (eventTypesCreateResponseSuccess | eventTypesCreateResponseError)

export const getEventTypesCreateUrl = () => {




  return `/api/event-types`
}

export const eventTypesCreate = async (createEventTypeRequest: CreateEventTypeRequest, options?: RequestInit): Promise<eventTypesCreateResponse> => {

  const res = await fetch(getEventTypesCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createEventTypeRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: eventTypesCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as eventTypesCreateResponse
}




export const getEventTypesCreateMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof eventTypesCreate>>, TError,{data: CreateEventTypeRequest}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof eventTypesCreate>>, TError,{data: CreateEventTypeRequest}, TContext> => {

const mutationKey = ['eventTypesCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventTypesCreate>>, {data: CreateEventTypeRequest}> = (props) => {
          const {data} = props ?? {};

          return  eventTypesCreate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EventTypesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof eventTypesCreate>>>
    export type EventTypesCreateMutationBody = CreateEventTypeRequest
    export type EventTypesCreateMutationError = ErrorResponse

    export const createEventTypesCreate = <TError = ErrorResponse,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof eventTypesCreate>>, TError,{data: CreateEventTypeRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof eventTypesCreate>>,
        TError,
        {data: CreateEventTypeRequest},
        TContext
      > => {
      return createMutation(() => ({ ...getEventTypesCreateMutationOptions(options?.()) }), queryClient);
    }
    /**
 * Partially update an event type by ID
 */
export type byIdUpdateResponse200 = {
  data: EventType
  status: 200
}

export type byIdUpdateResponse400 = {
  data: ErrorResponse
  status: 400
}

export type byIdUpdateResponse404 = {
  data: ErrorResponse
  status: 404
}

export type byIdUpdateResponseSuccess = (byIdUpdateResponse200) & {
  headers: Headers;
};
export type byIdUpdateResponseError = (byIdUpdateResponse400 | byIdUpdateResponse404) & {
  headers: Headers;
};

export type byIdUpdateResponse = (byIdUpdateResponseSuccess | byIdUpdateResponseError)

export const getByIdUpdateUrl = (id: string,) => {




  return `/api/event-types/${id}`
}

export const byIdUpdate = async (id: string,
    updateEventTypeRequest: UpdateEventTypeRequest, options?: RequestInit): Promise<byIdUpdateResponse> => {

  const res = await fetch(getByIdUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateEventTypeRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: byIdUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as byIdUpdateResponse
}




export const getByIdUpdateMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof byIdUpdate>>, TError,{id: string;data: UpdateEventTypeRequest}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof byIdUpdate>>, TError,{id: string;data: UpdateEventTypeRequest}, TContext> => {

const mutationKey = ['byIdUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof byIdUpdate>>, {id: string;data: UpdateEventTypeRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  byIdUpdate(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ByIdUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof byIdUpdate>>>
    export type ByIdUpdateMutationBody = UpdateEventTypeRequest
    export type ByIdUpdateMutationError = ErrorResponse

    export const createByIdUpdate = <TError = ErrorResponse,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof byIdUpdate>>, TError,{id: string;data: UpdateEventTypeRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof byIdUpdate>>,
        TError,
        {id: string;data: UpdateEventTypeRequest},
        TContext
      > => {
      return createMutation(() => ({ ...getByIdUpdateMutationOptions(options?.()) }), queryClient);
    }
    /**
 * Delete an event type by ID. Existing bookings are preserved (denormalized).
 */
export type byIdDeleteResponse204 = {
  data: void
  status: 204
}

export type byIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type byIdDeleteResponseSuccess = (byIdDeleteResponse204) & {
  headers: Headers;
};
export type byIdDeleteResponseError = (byIdDeleteResponse404) & {
  headers: Headers;
};

export type byIdDeleteResponse = (byIdDeleteResponseSuccess | byIdDeleteResponseError)

export const getByIdDeleteUrl = (id: string,) => {




  return `/api/event-types/${id}`
}

export const byIdDelete = async (id: string, options?: RequestInit): Promise<byIdDeleteResponse> => {

  const res = await fetch(getByIdDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: byIdDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as byIdDeleteResponse
}




export const getByIdDeleteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof byIdDelete>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof byIdDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['byIdDelete'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof byIdDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  byIdDelete(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ByIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof byIdDelete>>>

    export type ByIdDeleteMutationError = ErrorResponse

    export const createByIdDelete = <TError = ErrorResponse,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof byIdDelete>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof byIdDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return createMutation(() => ({ ...getByIdDeleteMutationOptions(options?.()) }), queryClient);
    }
    /**
 * Get slots for a specific date and event type. Date format: YYYY-MM-DD. Returns all 30-min slots within working hours with availability status.
 */
export type slotsListResponse200 = {
  data: Slot[]
  status: 200
}

export type slotsListResponse400 = {
  data: ErrorResponse
  status: 400
}

export type slotsListResponseSuccess = (slotsListResponse200) & {
  headers: Headers;
};
export type slotsListResponseError = (slotsListResponse400) & {
  headers: Headers;
};

export type slotsListResponse = (slotsListResponseSuccess | slotsListResponseError)

export const getSlotsListUrl = (params: SlotsListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/slots?${stringifiedParams}` : `/api/slots`
}

export const slotsList = async (params: SlotsListParams, options?: RequestInit): Promise<slotsListResponse> => {

  const res = await fetch(getSlotsListUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: slotsListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as slotsListResponse
}





export const getSlotsListQueryKey = (params?: SlotsListParams,) => {
    return [
    `/api/slots`, ...(params ? [params] : [])
    ] as const;
    }


export const getSlotsListQueryOptions = <TData = Awaited<ReturnType<typeof slotsList>>, TError = ErrorResponse>(params: SlotsListParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof slotsList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSlotsListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof slotsList>>> = ({ signal }) => slotsList(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof slotsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SlotsListQueryResult = NonNullable<Awaited<ReturnType<typeof slotsList>>>
export type SlotsListQueryError = ErrorResponse



export function createSlotsList<TData = Awaited<ReturnType<typeof slotsList>>, TError = ErrorResponse>(
 params: () =>  SlotsListParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof slotsList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getSlotsListQueryOptions(params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}






