/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Calendar Booking API
 * OpenAPI spec version: 0.0.0
 */
import type { Duration } from './duration';

/**
 * A booking made by a guest. Event type data (eventTypeName, duration) is denormalized — copied at creation time so bookings remain self-contained even if the event type is later modified or deleted.
 */
export interface Booking {
  /** Unique identifier (UUID v4) */
  id: string;
  /** ID of the event type at the time of booking (not a FK) */
  eventTypeId: string;
  /** Name of the event type, copied at creation time */
  eventTypeName: string;
  /** Meeting duration in minutes, copied at creation time */
  duration: Duration;
  /** Guest's name */
  guestName: string;
  /** Guest's email address */
  guestEmail: string;
  /** Start of the 30-min slot in UTC. Must be on a 30-min boundary within working hours (09:00–16:30) */
  startTime: string;
  /** End of the 30-min slot (startTime + 30 min) */
  endTime: string;
  /** Creation timestamp in UTC ISO 8601 */
  createdAt: string;
}
