/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Calendar Booking API
 * OpenAPI spec version: 0.0.0
 */
import type { Duration } from './duration';

/**
 * Request body for creating a new event type
 */
export interface CreateEventTypeRequest {
  /**
     * Display name, must not be empty
     * @minLength 1
     */
  name: string;
  /** Meeting duration: 10, 15, 20, or 30 minutes */
  duration: Duration;
}
