/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Calendar Booking API
 * OpenAPI spec version: 0.0.0
 */

/**
 * Request body for creating a booking. Backend looks up eventType to populate denormalized fields.
 */
export interface CreateBookingRequest {
  /** ID of the event type to book */
  eventTypeId: string;
  /**
     * Guest's name, must not be empty
     * @minLength 1
     */
  guestName: string;
  /** Guest's email, must be a valid email address */
  guestEmail: string;
  /** Desired slot start time in UTC. Must be 30-min aligned, within 09:00–16:30, within 14 days from now */
  startTime: string;
}
