/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Calendar Booking API
 * OpenAPI spec version: 0.0.0
 */

/**
 * Meeting duration in minutes. Meetings shorter than 30 min still occupy a full 30-min slot.
 */
export type Duration = typeof Duration[keyof typeof Duration];


export const Duration = {
  NUMBER_10: 10,
  NUMBER_15: 15,
  NUMBER_20: 20,
  NUMBER_30: 30,
} as const;
