/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Calendar Booking API
 * OpenAPI spec version: 0.0.0
 */

/**
 * Standard error response returned for 400, 404, 409 errors
 */
export interface ErrorResponse {
  /** Human-readable error description */
  message: string;
}
