/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Calendar Booking API
 * OpenAPI spec version: 0.0.0
 */
import type { Duration } from './duration';

/**
 * Type of event that guests can book. Created and managed by the calendar owner.
 */
export interface EventType {
  /** Unique identifier (UUID v4) */
  id: string;
  /**
     * Display name of the event type, shown to guests
     * @minLength 1
     */
  name: string;
  /** Duration of the meeting in minutes */
  duration: Duration;
  /** Creation timestamp in UTC ISO 8601 */
  createdAt: string;
}
