/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Calendar Booking API
 * OpenAPI spec version: 0.0.0
 */

export type SlotsListParams = {
/**
 * Date in YYYY-MM-DD format, must be within 14 days from today
 */
date: string;
/**
 * Event type ID — used to validate existence and provide context
 */
eventTypeId: string;
};
