/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Calendar Booking API
 * OpenAPI spec version: 0.0.0
 */

/**
 * A 30-minute time slot. Availability is global — a slot occupied by any event type is unavailable for all.
 */
export interface Slot {
  /** Slot start time in UTC */
  startTime: string;
  /** Slot end time in UTC (startTime + 30 min) */
  endTime: string;
  /** true if slot is free for booking, false if already taken */
  available: boolean;
}
