/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Calendar Booking API
 * OpenAPI spec version: 0.0.0
 */
import type { Duration } from './duration';

/**
 * Request body for partial update of an event type
 */
export interface UpdateEventTypeRequest {
  /**
     * New display name, must not be empty if provided
     * @minLength 1
     */
  name?: string;
  /** New duration in minutes */
  duration?: Duration;
}
